import { Component, OnInit } from '@angular/core';
import { FormControl } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import { TaskService } from '../_services/task.service';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';
import { Task } from '../model/Task';
import { MatDialog, MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { Inject } from '@angular/core';
import { DialogOverviewExampleDialog } from '../dialog-form-add-directory/DialogOverviewExampleDialog';
import { MatSnackBar } from '@angular/material/snack-bar';
// this is auto-generated by ASP.NET
declare var $: any;

export function FormatString(maxLength: number, inputString: string, finalString) {
  if (inputString.length > maxLength) {
    return finalString.concat(inputString.substring(0, maxLength), "\n", inputString.substring(maxLength, inputString.length))
  }
  else return inputString;
}
@Component({
  selector: 'app-edit-task-page',
  templateUrl: './edit-task-page.component.html',
  styleUrls: ['./edit-task-page.component.css']
})
export class EditTaskPageComponent implements OnInit {
  constructor(private taskService: TaskService, private router: Router, private formBuilder: FormBuilder, public dialog: MatDialog, private route: ActivatedRoute, private snackBar: MatSnackBar) { }
  date = '';
  task;
  directoriesList: Array<any> = [];
  form: FormGroup = this.formBuilder.group({
    header: [null, Validators.required],
    description: [null, Validators.required],
  });
  directoryName: string = "";
  task_id!: number;
  isInDirectory: boolean = false;

  ngOnInit(): void {
    this.getUserDirectories();
    this.getTaskById(this.task_id = this.route.snapshot.params['id']);
  }

  onSubmit() {
    this.task.description = FormatString(40, this.task.description, "");
    this.taskService.updateTask(this.task).subscribe(
      data => {
        console.log(data);
        this.returnToTaskPage();
        this.openSnackBar("Selected task has been updated", "Confirm");
      },
      err => {
        console.log("oops", err);
      });
  }

  returnToTaskPage() {
    this.router.navigate(['/tasks']);
  }

  getUserDirectories() {
    this.taskService.getUserDirectories().subscribe(
      data => {
        console.log(data);
        this.directoriesList = data;
      },
      err => {
        console.log("oops", err);
      });
  }
  getTaskById(task_Id: number) {
    this.taskService.getTaskById(task_Id).subscribe(
      data => {
        console.log(data);
        if (data.directory != null) {
          this.isInDirectory = true;
        }
        else {
          this.isInDirectory = false;
        }
        this.task = data;
      },
      err => {
        console.log("oops", err);
      });
  }
  selectDirectory(directory_Id: number) {
    this.task.directory_Id = directory_Id;
  }

  createDirectory(directory: string) {
    if (directory.length > 7) {
      this.openSnackBar("Length shoud be less or 6 symbols", "Confirm");
      return;
    }
    if (this.directoriesList.length > 4) {
      this.openSnackBar("The maximum number of directories - 5", "Confirm");
      return;
    }
    this.taskService.addDirectory(directory).subscribe(
      data => {
        this.dialog.closeAll();
        this.getUserDirectories();
      },
      err => {
        console.log("oops", err);
      });
  }
  openDialog(): void {
    const dialogRef = this.dialog.open(DialogOverviewExampleDialog, {
      width: '250px',
      data: { directoryName: this.directoryName }
    });

    dialogRef.afterClosed().subscribe(result => {
      this.directoryName = result;
      this.createDirectory(result);
    });
  }
  openSnackBar(message: string, action: string) {
    this.snackBar.open(message, action);
  }
}